# SYSTEM Operation
CHECKING_LOOP_NUM=5 # 루프를 몇번돌고 checking 작업을 할 것인지 정해줌

# TELEGRAM API

# MOUSE CONTROL
MOUSE_LOCATION_PRECISION=20
MOUSE_AUTO_INTERVAL=50

MOUSE_SCROLL_LENGH_RATIO=20


# KTX Reservation
RESERVATION_CHECK_MESSAGE="예약하기(할인선택)"